ValueError: Error raised by inference API: Input validation error: `inputs` must have less than 1024 tokens. Given: 1073
Traceback:
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\app.py", line 114, in <module>
    main()
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\app.py", line 111, in main
    handle_user_input(query, VectorStore, select_llm)
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\app.py", line 62, in handle_user_input
    response = chain.run(input_documents=docs, question=query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\base.py", line 510, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\base.py", line 310, in __call__
    raise e
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\combine_documents\base.py", line 122, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\combine_documents\stuff.py", line 171, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\llm.py", line 298, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\base.py", line 310, in __call__
    raise e
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\llm.py", line 108, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\chains\llm.py", line 120, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\llms\base.py", line 507, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\llms\base.py", line 656, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\llms\base.py", line 544, in _generate_helper
    raise e
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\llms\base.py", line 531, in _generate_helper
    self._generate(
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\llms\base.py", line 1053, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
File "C:\Users\Aliff Fahmi\Documents\GitHub\Local-LLM-and-OpenAI-PDF-QA\venv\Lib\site-packages\langchain\llms\huggingface_hub.py", line 112, in _call
    raise ValueError(f"Error raised by inference API: {response['error']}")